use_default_settings: true
server:
  secret_key: "your-super-secret-key-2026-change-in-prod"
  limiter: false
  bind_address: "0.0.0.0"
  port: 8080
search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "zh-TW"
redis:
  url: "redis://redis:6379/0"
formats:
  - html
  - json
engines:
  - name: "google"
    shortcut: "g"

